# Generated by Django 3.2.25 on 2025-06-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_add_sca_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='paper_size',
            field=models.CharField(choices=[('letter', 'Letter (8.5" × 11")'), ('a4', 'A4 (210mm × 297mm)')], default='letter', help_text='Select paper size for PDF reports', max_length=10),
        ),
    ]
