# Generated by Django 4.2 on 2026-06-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_auto_20241114_2049"),
        ("reports", "0010_auto_v4_0_combined"),
    ]

    operations = []
