# Generated by Django 2.2.18 on 2024-11-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_auto_20210323_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['number'], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
