# Generated by Django 4.2 on 2026-06-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0020_auto_20241114_2049"),
        ("units", "0021_auto_v4_0_combined"),
    ]

    operations = []
