# Generated by Django 4.2 on 2026-06-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0017_auto_20241114_2049"),
        ("parts", "0018_auto_v4_0_combined"),
    ]

    operations = []
